# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 20:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=200)),
                ('tweet_location', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('tweet_date', models.DateTimeField(verbose_name=b'date tweeted')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Phrase')),
            ],
        ),
        migrations.CreateModel(
            name='TweetTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tweeted', models.DateTimeField(verbose_name=b'date tweeted')),
                ('days_tweets', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
