# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 15:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_phrases_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tweeted', models.DateTimeField(verbose_name=b'date tweeted')),
                ('days_tweets', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
